name: update awesome-stars
on:
  workflow_dispatch:
  schedule:
  - cron: 0 12 * * 1
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
1
name: update awesome-stars
2
on:
3
  workflow_dispatch:
4
  schedule:
5
  - cron: 0 12 * * 1
6
jobs:
7
  awesome-stars:
8
    name: update awesome-stars
9
    runs-on: ubuntu-latest
10
    steps:
11
    - uses: actions/checkout@v1
12
    - name: Set up Python
13
      uses: actions/setup-python@v1
14
      with:
15
        python-version: 3.7
16
    - name: Install dependencies
17
      run: |
18
        python -m pip install --upgrade pip
19
        pip install starred
20
    - name: update repo
21
      env:
22
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
23
      run: starred --username zubayrrr --repository stars --sort --token ${GITHUB_TOKEN} --message 'Update README.md with latest stars'
}
      run: starred --username zubayrrr --repository stars --sort --token ${GITHUB_TOKEN} --message 'Update README.md with latest stars'
